server.port=8080

# Kết nối lên Cloud Aiven
spring.datasource.url=jdbc:mysql://mysql-XXX.aivencloud.com:16218/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=NHAP_MAT_KHAU_AIVEN_VAO_DAY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- MAIL CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ngonlanh.foodweb@gmail.com
spring.mail.password=NHAP_APP_PASSWORD_GMAIL_VAO_DAY
# ... (các cấu hình khác giữ nguyên)